apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 32777
      targetPort: 32777
      nodePort: 32700
  type: NodePort

